import { TechnicianMyTaskStats, TechnicianMyTaskItem } from '../types';

export const getTechnicianMyTaskStats = async (): Promise<TechnicianMyTaskStats> => {
  return {
    all: 24,
    pending: 5,
    inProgress: 4,
    waiting: 2,
    overdue: 1,
    completedToday: 12,
  };
};

export const getTechnicianMyTasks = async (): Promise<TechnicianMyTaskItem[]> => {
  return [
    {
      id: 'WO-6705-00123',
      woNumber: 'WO-6705-00123',
      createdDate: 'สร้างเมื่อ 20 พ.ค. 2567',
      taskType: 'แจ้งซ่อม',
      taskIcon: 'Wrench',
      taskIconColor: 'text-amber-600',
      taskIconBg: 'bg-amber-50',
      assetName: 'เครื่องปรับอากาศ แบบแขวน',
      location: 'อาคารสำนักงาน ชั้น 2 ห้อง 201',
      reporterName: 'น.ส. กานต์พิชชา',
      reporterDept: 'กองคลัง',
      priority: 'สูง',
      priorityColor: 'text-rose-600 bg-rose-50',
      dueDate: '21 พ.ค. 2567',
      dueTime: '17:00 น.',
      overdueText: 'เหลือเวลา 2 ชั่วโมง',
      status: 'กำลังดำเนินการ',
      statusColor: 'text-blue-600',
      statusBg: 'bg-blue-50',
      actionText: 'ดำเนินการต่อ',
    },
    {
      id: 'WO-6705-00124',
      woNumber: 'WO-6705-00124',
      createdDate: 'สร้างเมื่อ 20 พ.ค. 2567',
      taskType: 'บำรุงรักษา (PM)',
      taskIcon: 'Settings',
      taskIconColor: 'text-blue-600',
      taskIconBg: 'bg-blue-50',
      assetName: 'ตู้ควบคุมไฟฟ้า MDB',
      location: 'อาคาร A ชั้น 1',
      reporterName: 'นายอนันต์',
      reporterDept: 'กองช่าง',
      priority: 'ปานกลาง',
      priorityColor: 'text-amber-600 bg-amber-50',
      dueDate: '22 พ.ค. 2567',
      dueTime: '12:00 น.',
      status: 'รอดำเนินการ',
      statusColor: 'text-amber-600',
      statusBg: 'bg-amber-50',
      actionText: 'เริ่มงาน',
    },
    {
      id: 'WO-6705-00125',
      woNumber: 'WO-6705-00125',
      createdDate: 'สร้างเมื่อ 19 พ.ค. 2567',
      taskType: 'ตรวจสอบ',
      taskIcon: 'ClipboardCheck',
      taskIconColor: 'text-purple-600',
      taskIconBg: 'bg-purple-50',
      assetName: 'ปั๊มน้ำหอยโข่ง 3 HP',
      location: 'สถานีสูบน้ำ หนองมน',
      reporterName: 'นายเอกชัย',
      reporterDept: 'กองช่าง',
      priority: 'ต่ำ',
      priorityColor: 'text-emerald-600 bg-emerald-50',
      dueDate: '20 พ.ค. 2567',
      dueTime: '16:00 น.',
      overdueText: 'เกินกำหนด 1 วัน',
      status: 'รอดำเนินการ',
      statusColor: 'text-rose-600',
      statusBg: 'bg-rose-50',
      actionText: 'ดูรายละเอียด',
    },
  ];
};
