import { Send, Users, Eye, ThumbsUp, AlertCircle } from 'lucide-react';
import type { CardMetricProps } from '@/components/dashboard/CardMetric';

export const communicationOverviewStats: CardMetricProps[] = [
  {
    icon: Send,
    value: 28,
    unit: 'ข้อความ',
    title: 'ข้อความที่ส่งทั้งหมด',
    subValue: 27,
    subUnit: '% เทียบกับเมื่อวาน',
    positiveData: true,
    className: 'border-slate-100',
    classNameForIcon: 'bg-blue-50 text-blue-500',
  },
  {
    icon: Users,
    value: 856250,
    unit: 'คน',
    title: 'ประชาชนเข้าถึง',
    subValue: 18,
    subUnit: '% เทียบกับเมื่อวาน',
    positiveData: true,
    className: 'border-slate-100',
    classNameForIcon: 'bg-emerald-50 text-emerald-600',
  },
  {
    icon: Eye,
    value: 72.4,
    unit: '% (Reach)',
    title: 'อัตราการเปิดรับ',
    subValue: 9.6,
    subUnit: '% เทียบกับเมื่อวาน',
    positiveData: true,
    className: 'border-slate-100',
    classNameForIcon: 'bg-purple-50 text-purple-500',
  },
  {
    icon: ThumbsUp,
    value: 12.8,
    unit: '% (Engagement)',
    title: 'อัตราการมีส่วนร่วม',
    subValue: 2.3,
    subUnit: '% เทียบกับเมื่อวาน',
    positiveData: true,
    className: 'border-slate-100',
    classNameForIcon: 'bg-orange-50 text-orange-500',
  },
  {
    icon: AlertCircle,
    value: 5,
    unit: 'ข้อความ',
    title: 'ข้อความแจ้งเตือนสำคัญ',
    subValue: -2,
    subUnit: ' เทียบกับเมื่อวาน',
    positiveData: false,
    className: 'border-slate-100',
    classNameForIcon: 'bg-rose-50 text-rose-500',
  },
];
