import { CloudRain, Thermometer, Wind, Users } from 'lucide-react';
import type { CardMetricWLineChartProps } from '@/components/dashboard/CardMetricWLineChart';

export const dataWithinDay: Omit<CardMetricWLineChartProps, 'className'>[] = [
    {
        title: "สภาพอากาศ",
        icon: CloudRain,
        valueLabel: "ฝน",
        valueText: "60%",
        subLabel: "ช่วงบ่าย - ค่ำ",
        percentage: 10,
        positiveData: true,
        chartData: [12, 15, 18, 24, 32, 46, 40, 30, 26, 22],
        chartColorClass: "text-blue-500",
    },
    {
        title: "อุณหภูมิ",
        icon: Thermometer,
        valueLabel: "อุณหภูมิ",
        valueText: "34°C",
        subLabel: "เทียบกับเมื่อวาน",
        percentage: 4.2,
        positiveData: false,
        chartData: [27, 28, 29, 31, 33, 34, 34, 33, 31, 29],
        chartColorClass: "text-orange-500",
    },
    {
        title: "ความเร็วลม",
        icon: Wind,
        valueLabel: "ลม",
        valueText: "18 กม./ชม.",
        subLabel: "ช่วงเช้า - เที่ยง",
        percentage: -6.5,
        positiveData: true,
        chartData: [10, 12, 14, 20, 18, 15, 13, 11, 9, 8],
        chartColorClass: "text-emerald-500",
    },
    {
        title: "นักท่องเที่ยว",
        icon: Users,
        valueLabel: "จำนวน",
        valueText: "1,240 คน",
        subLabel: "เทียบกับเมื่อวาน",
        percentage: 18,
        positiveData: true,
        chartData: [400, 520, 680, 820, 950, 1100, 1180, 1240, 1200, 1150],
        chartColorClass: "text-violet-500",
    },
    {
        title: "ความเร็วลม",
        icon: Wind,
        valueLabel: "ลม",
        valueText: "18 กม./ชม.",
        subLabel: "ช่วงเช้า - เที่ยง",
        percentage: -6.5,
        positiveData: true,
        chartData: [10, 12, 14, 20, 18, 15, 13, 11, 9, 8],
        chartColorClass: "text-emerald-500",
    },
];
