// Generated by inspecting the `core` schema of Supabase project wmcliqjttbpihjcosmmc
// (cityzen_application_layer) — only the directory-cache tables consumed by
// src/lib/directory-cache.ts. Regenerate/extend if that file starts using more tables.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: { [_ in never]: never };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
  core: {
    Tables: {
      tenant_directory_cache: {
        Row: {
          thundercore_tenant_id: string;
          tenant_type: string | null;
          code: string | null;
          name: string;
          status: string | null;
          synced_at: string;
        };
        Insert: {
          thundercore_tenant_id: string;
          tenant_type?: string | null;
          code?: string | null;
          name: string;
          status?: string | null;
          synced_at?: string;
        };
        Update: {
          thundercore_tenant_id?: string;
          tenant_type?: string | null;
          code?: string | null;
          name?: string;
          status?: string | null;
          synced_at?: string;
        };
        Relationships: [];
      };
      department_directory_cache: {
        Row: {
          thundercore_department_id: string;
          thundercore_tenant_id: string;
          department_type: string | null;
          abbreviation: string | null;
          name: string;
          status: string | null;
          synced_at: string;
        };
        Insert: {
          thundercore_department_id: string;
          thundercore_tenant_id: string;
          department_type?: string | null;
          abbreviation?: string | null;
          name: string;
          status?: string | null;
          synced_at?: string;
        };
        Update: {
          thundercore_department_id?: string;
          thundercore_tenant_id?: string;
          department_type?: string | null;
          abbreviation?: string | null;
          name?: string;
          status?: string | null;
          synced_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "department_directory_cache_thundercore_tenant_id_fkey";
            columns: ["thundercore_tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenant_directory_cache";
            referencedColumns: ["thundercore_tenant_id"];
          },
        ];
      };
      user_directory_cache: {
        Row: {
          thundercore_user_id: string;
          display_name: string;
          email: string | null;
          avatar_url: string | null;
          role_label: string | null;
          synced_at: string;
        };
        Insert: {
          thundercore_user_id: string;
          display_name: string;
          email?: string | null;
          avatar_url?: string | null;
          role_label?: string | null;
          synced_at?: string;
        };
        Update: {
          thundercore_user_id?: string;
          display_name?: string;
          email?: string | null;
          avatar_url?: string | null;
          role_label?: string | null;
          synced_at?: string;
        };
        Relationships: [];
      };
      membership_directory_cache: {
        Row: {
          thundercore_user_id: string;
          thundercore_tenant_id: string;
          status: string;
          role_codes: string[];
          synced_at: string;
        };
        Insert: {
          thundercore_user_id: string;
          thundercore_tenant_id: string;
          status?: string;
          role_codes?: string[];
          synced_at?: string;
        };
        Update: {
          thundercore_user_id?: string;
          thundercore_tenant_id?: string;
          status?: string;
          role_codes?: string[];
          synced_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "membership_directory_cache_thundercore_tenant_id_fkey";
            columns: ["thundercore_tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenant_directory_cache";
            referencedColumns: ["thundercore_tenant_id"];
          },
          {
            foreignKeyName: "membership_directory_cache_thundercore_user_id_fkey";
            columns: ["thundercore_user_id"];
            isOneToOne: false;
            referencedRelation: "user_directory_cache";
            referencedColumns: ["thundercore_user_id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
