import { CheckCircle2, UsersRound, Clock, Coins, Heart } from 'lucide-react';
import type { CardMetricProps } from '@/components/dashboard/CardMetric';

export const keyOutcomeStats: CardMetricProps[] = [
  {
    icon: CheckCircle2,
    value: 85,
    unit: '%',
    title: 'การกิจสำเร็จตามเป้าหมาย',
    subValue: 18,
    subUnit: '% จากสัปดาห์ก่อน',
    positiveData: true,
    className: 'border-slate-100',
    classNameForIcon: 'bg-emerald-50 text-emerald-500',
  },
  {
    icon: UsersRound,
    value: 32,
    unit: '%',
    title: 'ประชาชนได้รับผลกระทบลดลง',
    subValue: -32,
    subUnit: '% จากสัปดาห์ก่อน',
    positiveData: false,
    className: 'border-slate-100',
    classNameForIcon: 'bg-purple-50 text-purple-500',
  },
  {
    icon: Clock,
    value: 28,
    unit: '%',
    title: 'เวลาตอบสนองเฉลี่ยลดลง',
    subValue: -28,
    subUnit: '% จากสัปดาห์ก่อน',
    positiveData: false,
    className: 'border-slate-100',
    classNameForIcon: 'bg-blue-50 text-blue-500',
  },
  {
    icon: Coins,
    value: 92,
    unit: '%',
    title: 'งบประมาณใช้จ่ายคุ้มค่า',
    subValue: 12,
    subUnit: '% จากสัปดาห์ก่อน',
    positiveData: true,
    className: 'border-slate-100',
    classNameForIcon: 'bg-yellow-50 text-yellow-500',
  },
  {
    icon: Heart,
    value: 4.6,
    unit: '/5',
    title: 'ความพึงพอใจประชาชน',
    subValue: 0.6,
    subUnit: ' จากสัปดาห์ก่อน',
    positiveData: true,
    className: 'border-slate-100',
    classNameForIcon: 'bg-rose-50 text-rose-500',
  },
];
